# Rocket Configuration for Nexus API Server
#
# IMPORTANT: For Docker deployment, these values are overridden by environment variables
# in docker-compose.yml. This file is primarily for local development.
#
# Environment Variable Override:
# You can override any configuration using environment variables with the ROCKET_ prefix:
#
#   export ROCKET_DATABASES='{nexus_db={url="postgres://user:pass@host:port/db"}, bulk_write_db={url="postgres://user:pass@host:port/db"}}'
#   export ROCKET_ADDRESS="0.0.0.0"
#   export ROCKET_PORT="8000"
#
# For local development, update the database URLs below to match your PostgreSQL setup.

[default]
address = "0.0.0.0"
port = 8000

# Main database connection pool
# Optimized for read-heavy API workloads with parallel query support
[default.databases.nexus_db]
url = "postgres://postgres:changeme456@localhost:5432/nexus"
min_connections = 8
max_connections = 32
connect_timeout = 5
idle_timeout = 300
max_lifetime = 1800  # 30 minutes

# Separate pool optimized for bulk write operations
# Higher connection count for parallel bulk imports
[default.databases.bulk_write_db]
url = "postgres://postgres:changeme456@localhost:5432/nexus"
min_connections = 12
max_connections = 24
connect_timeout = 10
idle_timeout = 600
max_lifetime = 3600  # 60 minutes
